# Default values for todo-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dwgao/todo-service
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: "todo-service"
fullnameOverride: "todo-service"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

env:
  profile: "dev"
  java:
    opts: "-Xmx480m -Xms480m"
  eureka:
    host: eureka-server
    port: 8080
  config:
    server: config-server

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
