apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pinpoint.fullname" . }}
  labels:
{{ include "pinpoint.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pinpoint.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pinpoint.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "pinpoint-collector"
            - "pinpoint-hbase"
            - "pinpoint-web"
      containers:
        - name: pinpoint-hbase
          image: "{{ .Values.image.repository.hbase }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HBASE_OPTS
              value: "{{ .Values.env.hbase.opts }}"
          ports:
            - containerPort: 2181
              protocol: TCP
              name: tcp-2181
            - containerPort: 60000
              protocol: TCP
              name: tcp-60000
            - containerPort: 16010
              protocol: TCP
              name: http-16010
            - containerPort: 60020
              protocol: TCP
              name: tcp-60020
            - containerPort: 16030
              protocol: TCP
              name: http-16030
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: pinpoint-collector
          image: "{{ .Values.image.repository.collector }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JAVA_OPTS
              value: "{{ .Values.env.java.opts }}"
            - name: HBASE_HOST
              value: "{{ .Values.env.hbase.host }}"
            - name: HBASE_PORT
              value: "{{ .Values.env.hbase.port }}"
            - name: DEBUG_LEVEL
              value: "{{ .Values.env.debug.level }}"
            - name: FLINK_CLUSTER_ENABLE
              value: "false"
            - name: CLUSTER_ENABLE
              value: "false"
          ports:
            - containerPort: 9994
              protocol: TCP
              name: tcp-9994
            - containerPort: 9995
              protocol: TCP
              name: tcp-9995
            - containerPort: 9996
              protocol: TCP
              name: tcp-9996
            - containerPort: 9995
              protocol: UDP
              name: udp-9995
            - containerPort: 9996
              protocol: UDP
              name: udp-9996
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: pinpoint-web
          image: "{{ .Values.image.repository.web }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JAVA_OPTS
              value: "{{ .Values.env.java.opts }}"
            - name: HBASE_HOST
              value: "{{ .Values.env.hbase.host }}"
            - name: HBASE_PORT
              value: "{{ .Values.env.hbase.port }}"
            - name: DEBUG_LEVEL
              value: "{{ .Values.env.debug.level }}"
            - name: FLINK_CLUSTER_ENABLE
              value: "false"
            - name: CLUSTER_ENABLE
              value: "false"
            - name: ANALYTICS
              value: "false"
            - name: BATCH_ENABLE
              value: "false"
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http-8080
            - containerPort: 9997
              protocol: TCP
              name: http-9997
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
