apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
{{ include "rabbitmq.labels" . | indent 4 }}
spec:
  type: NodePort
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: tcp-5672
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: http-15672
  selector:
    app.kubernetes.io/name: {{ include "rabbitmq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
