apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
{{ include "rabbitmq.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.amqp.port }}
      targetPort: {{ .Values.service.amqp.port }}
      protocol: TCP
      name: tcp-{{ .Values.service.amqp.port }}
    - port: {{ .Values.service.management.port }}
      targetPort: {{ .Values.service.management.port }}
      protocol: TCP
      name: http-{{ .Values.service.management.port }}
  selector:
    app.kubernetes.io/name: {{ include "rabbitmq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
