# Default values for pinpoint.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository:
    hbase: dwgao/pinpoint-hbase
    collector: dwgao/pinpoint-collector
    web: dwgao/pinpoint-web
  tag: v1.8.4
  pullPolicy: Always

imagePullSecrets: []
nameOverride: "pinpoint"
fullnameOverride: "pinpoint"

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

env:
  hbase:
    opts: "-Xmx1g -Xms1g"
  java:
    opts: "-Xmx1g -Xms1g"
  hbase:
    host: pinpoint-hbase
    port: 2181
  debug:
    level: INFO

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1.5Gi

nodeSelector: {}

tolerations: []

affinity: {}
